Repository monero-project/monero, pull requests merged in 2024-07, with the labels that each got.

#8619 wallet: background sync with just the view key [master]
  src/cryptonote_basic/account.cpp
  src/cryptonote_basic/account.h
  src/cryptonote_config.h
  src/simplewallet/simplewallet.cpp
  src/simplewallet/simplewallet.h
  src/wallet/api/wallet.cpp
  src/wallet/api/wallet.h
  src/wallet/api/wallet2_api.h
  src/wallet/wallet2.cpp
  src/wallet/wallet2.h
  src/wallet/wallet_errors.h
  src/wallet/wallet_rpc_server.cpp
  src/wallet/wallet_rpc_server.h
  src/wallet/wallet_rpc_server_commands_defs.h
  src/wallet/wallet_rpc_server_error_codes.h
  tests/functional_tests/transfer.py
  tests/functional_tests/util_resources.py
  tests/functional_tests/wallet.py
  tests/unit_tests/wipeable_string.cpp
  utils/python-rpc/framework/wallet.py
Labels: pending review, feature, important, in progress, allarch, wallet

#9114 Add support for Loongarch
  CMakeLists.txt
  contrib/depends/packages/openssl.mk
  contrib/depends/toolchain.cmake.in
Labels: cmake

#9215 remove repetitive word
  contrib/epee/README.md
  src/device/log.hpp
  src/multisig/multisig_account_kex_impl.cpp
Labels: low priority, documentation

#9278 add sum of amounts for `unspent_outputs`
  src/simplewallet/simplewallet.cpp
Labels: easy, wallet

#9288 BlockchainDB: remove lock/unlock methods
  src/blockchain_db/blockchain_db.h
  src/blockchain_db/lmdb/db_lmdb.cpp
  src/blockchain_db/lmdb/db_lmdb.h
  src/blockchain_db/testdb.h
Labels: enhancement

#9289 BlockchainDB: shorter fixup()
  src/blockchain_db/blockchain_db.cpp
Labels: enhancement, pending review

#9324 README.md: sponsors;remove forked networking/globee
  README.md
Labels: documentation

#9343 wallet: fetch pool txs in pruned form
  src/wallet/wallet2.cpp
Labels: wallet

#9344 wallet2: validate fetched block height and parent hash
  src/wallet/wallet2.cpp
  src/wallet/wallet2.h
Labels: pending review, wallet

#9346 src: update checkpoints to match v0.18.3.4
  src/blocks/checkpoints.dat
  src/checkpoints/checkpoints.cpp
  src/cryptonote_core/blockchain.cpp
Labels: pending review

#9347 contrib: fix compilation error for boost 1.85 [release-v0.18]
  contrib/epee/include/storages/portable_storage_val_converters.h
Labels: pending review

#9349 workflows: don't hardcode repo name
  .github/workflows/build.yml
  .github/workflows/depends.yml
Labels: easy

#9353 cryptonote_protocol: prevent duplicate txs in fluff queue
  src/cryptonote_protocol/levin_notify.cpp
  tests/unit_tests/levin.cpp
Labels: easy, daemon, networking

#9355 cryptonote_protocol: prevent duplicate txs in fluff queue [RELEASE]
  src/cryptonote_protocol/levin_notify.cpp
  tests/unit_tests/levin.cpp
Labels: daemon, networking

#9370 Fix ZMQ Tx Pruning
  src/serialization/json_object.cpp
  src/serialization/json_object.h
Labels: daemon

#9374 wallet: fetch pool txs in pruned form [RELEASE]
  src/wallet/wallet2.cpp
Labels: wallet

#9377 Fix ZMQ Tx Pruning [release 0.18]
  src/serialization/json_object.cpp
  src/serialization/json_object.h
Labels: daemon

#9379 wallet2: move get_rpc_status func to RPC server definition file
  src/rpc/core_rpc_server_commands_defs.h
  src/wallet/wallet2.cpp
  src/wallet/wallet2.h
Labels: wallet

#9382 Daemon RPC: high_height_ok req boolean field /getblocks.bin
  src/rpc/core_rpc_server.cpp
  src/rpc/core_rpc_server_commands_defs.h
Labels: daemon

#9383 Daemon RPC: /getblocks.bin return chain's top_block_hash in resp
  src/cryptonote_core/blockchain.cpp
  src/cryptonote_core/blockchain.h
  src/cryptonote_core/cryptonote_core.cpp
  src/cryptonote_core/cryptonote_core.h
  src/rpc/core_rpc_server.cpp
  src/rpc/core_rpc_server_commands_defs.h
  src/rpc/daemon_handler.cpp
  src/rpc/daemon_messages.h
Labels: daemon

#9386 chore: fix some comments
  tests/README.md
  tests/unit_tests/hardfork.cpp
  tests/unit_tests/logging.cpp
  tests/unit_tests/output_selection.cpp
Labels: low priority, documentation

#9392 epee: fix mlog filename compare bug.
  contrib/epee/src/mlog.cpp
Labels: easy

#9396 [RELEASE] epee: fix mlog filename compare bug.
  contrib/epee/src/mlog.cpp
Labels: easy
