Repository monero-project/monero, pull requests merged in 2024-03, with the labels that each got.

#9166 depends: eudev: update to 3.2.14
  contrib/depends/packages/eudev.mk
Labels: enhancement, build system

#9167 depends: libusb: update to 1.0.27
  contrib/depends/packages/libusb.mk
  contrib/depends/patches/libusb/fix_osx_avail.patch
Labels: enhancement, build system

#9168 depends: remove ccache
  contrib/depends/packages/native_ccache.mk
  contrib/depends/packages/packages.mk
Labels: enhancement, build system

#9169 depends: remove unwind
  contrib/depends/packages/unwind.mk
  contrib/depends/patches/unwind/fix_obj_order.patch
Labels: enhancement, build system

#9170 depends: add riscv64 to gitignore
  contrib/depends/.gitignore
Labels: enhancement, build system

#9179 actions: update to v4 actions
  .github/workflows/build.yml
  .github/workflows/copyright.yml
  .github/workflows/depends.yml
  .github/workflows/gitian.yml
Labels: enhancement

#9184 Remove instructions for Void Linux, add NixOS
  README.md
Labels: proposal, easy, linux

#9187 depends: add download commands for freebsd & android sources
  contrib/depends/Makefile
Labels: enhancement, build system

#9214 unit_tests: fix strtoul unit test
  tests/unit_tests/epee_utils.cpp
Labels: pending review, low priority, tests

#9217 unit_tests: fix strtoul unit test [release-v0.18]
  tests/unit_tests/epee_utils.cpp
Labels: tests

#9218 tx_memory_pool: make double spends a no-drop offense
  src/cryptonote_core/tx_pool.cpp
Labels: proposal, discussion

#9220 wallet2: adjust fee during backlog, fix set priority [release-v0.18]
  src/simplewallet/simplewallet.cpp
  src/wallet/wallet2.cpp
Labels: pending review, wallet

#9219 wallet2: adjust fee during backlog, fix set priority
  src/simplewallet/simplewallet.cpp
  src/wallet/wallet2.cpp
Labels: wallet

#9228 depends: add riscv64 linux build tag
  contrib/depends/toolchain.cmake.in
Labels: build system

#9229 depends: add riscv64 linux build tag [release-v0.18]
  contrib/depends/toolchain.cmake.in
Labels: build system

#9237 Revert "http_client: reduce number of packets sent for small bodies"
  contrib/epee/include/net/http_client.h
Labels: networking

#9238 Revert "http_client: reduce number of packets sent for small bodies" [RELEASE]
  contrib/epee/include/net/http_client.h
Labels: networking

#9239 build: prepare v0.18.3.3
  README.md
  contrib/gitian/DOCKRUN.md
  contrib/gitian/README.md
  src/blocks/checkpoints.dat
  src/checkpoints/checkpoints.cpp
  src/cryptonote_core/blockchain.cpp
  src/version.cpp.in
Labels: build system
