Repository monero-project/monero, pull requests merged in 2024-10, with the labels that each got.

#9450 build: fix build with Boost 1.85 and remove instances of viewkey logging
  CMakeLists.txt
  contrib/epee/include/serialization/keyvalue_serialization.h
  contrib/epee/include/span.h
  contrib/epee/include/string_tools.h
  src/crypto/crypto.h
  src/cryptonote_basic/cryptonote_format_utils.cpp
  src/cryptonote_core/cryptonote_tx_utils.cpp
  src/cryptonote_protocol/block_queue.cpp
  src/device/device_default.cpp
  src/lmdb/util.h
  src/simplewallet/simplewallet.cpp
  src/wallet/api/wallet.cpp
  src/wallet/wallet2.cpp
  src/wallet/wallet_rpc_server.cpp
  tests/benchmark.cpp
  tests/core_tests/multisig.cpp
  tests/functional_tests/make_test_signature.cc
  tests/unit_tests/crypto.cpp
  tests/unit_tests/multisig.cpp
  tests/unit_tests/serialization.cpp
Labels: enhancement

#9462 build: fix build with Boost 1.85 and remove instances of viewkey logging [RELEASE]
  CMakeLists.txt
  contrib/epee/include/serialization/keyvalue_serialization.h
  contrib/epee/include/span.h
  contrib/epee/include/string_tools.h
  src/crypto/crypto.h
  src/cryptonote_basic/cryptonote_format_utils.cpp
  src/cryptonote_core/cryptonote_tx_utils.cpp
  src/cryptonote_protocol/block_queue.cpp
  src/device/device_default.cpp
  src/lmdb/util.h
  src/simplewallet/simplewallet.cpp
  src/wallet/api/wallet.cpp
  src/wallet/wallet2.cpp
  src/wallet/wallet_rpc_server.cpp
  tests/benchmark.cpp
  tests/core_tests/multisig.cpp
  tests/functional_tests/make_test_signature.cc
  tests/unit_tests/crypto.cpp
  tests/unit_tests/multisig.cpp
  tests/unit_tests/serialization.cpp
Labels: enhancement

#9480 ci: fix windows msys2 build
  .github/workflows/build.yml
  cmake/CheckTrezor.cmake
Labels: build system

#9499 cmake: boost: fix header-only library search, bump minimum
  CMakeLists.txt
  README.md
Labels: enhancement, pending review, build system

#9517 cmake: boost: fix header-only library search, bump minimum [RELEASE]
  CMakeLists.txt
  README.md
Labels: build system

#9435 epee: string_tools: remove dot from get_extension
  contrib/epee/src/string_tools.cpp
  tests/unit_tests/epee_utils.cpp
Labels: easy
