Repository monero-project/monero, pull requests merged in 2024-01, with the labels that each got.

#9023 wallet: mitigate statistical dependence for decoy selection within rings
  src/wallet/wallet2.cpp
Labels: allarch, wallet

#9052 Fix EAGAIN bug in ZMQ-RPC/ZMQ-PUB
  src/rpc/zmq_server.cpp
Labels: bug, allarch

#9053 Fix EAGAIN bug in ZMQ-RPC/ZMQ-PUB [0.18]
  src/rpc/zmq_server.cpp
Labels: allarch

#9061 Add compile-time check for input iterators in ::wire array writing
  contrib/epee/include/serialization/wire/write.h
Labels: enhancement, allarch

#9069 serialization: fix infinite loops and clean up dispatching
  src/cryptonote_basic/tx_extra.h
  src/serialization/container.h
  src/serialization/debug_archive.h
  src/serialization/difficulty_type.h
  src/serialization/pair.h
  src/serialization/serialization.h
  src/serialization/tuple.h
  src/serialization/variant.h
  tests/unit_tests/serialization.cpp
Labels: enhancement, allarch

#9072 Change std::result_of to auto
  contrib/epee/src/http_auth.cpp
Labels: enhancement, allarch

#9076 cmake: silence FindPythonInterp warning
  CMakeLists.txt
Labels: cmake

#9079 Fix missing checks for IsObject in ZMQ jsonrpc reading
  src/rpc/daemon_messages.cpp
  tests/unit_tests/json_serialization.cpp
Labels: enhancement, allarch

#9080 Fix missing checks for IsObject in ZMQ jsonrpc reading [0.18]
  src/rpc/daemon_messages.cpp
  tests/unit_tests/json_serialization.cpp
Labels: enhancement, allarch

#9084 OpenBSD: node server fix IP localhost by aliasing
  tests/unit_tests/node_server.cpp
Labels: documentation

#9090 Cleanup scoped_ptr in src/common/dns_utils.cpp
  contrib/epee/include/net/http_base.h
  src/common/dns_utils.cpp
Labels: enhancement, easy, allarch

#9103 storages: add missing return
  contrib/epee/include/storages/portable_storage_from_bin.h
Labels: pending review, easy

#9111 workflows: copyright commit author
  .github/workflows/copyright.yml
Labels: easy, allarch

#9117 remove ARCH="x86-64" from Makefile
  Makefile
Labels: low priority, cmake

#9119 gpg_keys: add 0xfffc0000
  utils/gpg_keys/0xfffc0000.asc
Labels: low priority

#9126 CMake: only set policy CMP0148 to OLD if version >= 3.27
  CMakeLists.txt
Labels: cmake
