Repository monero-project/monero, pull requests merged in 2024-02, with the labels that each got.

#8861 wallet: feature: transfer amount with fee included
  src/simplewallet/simplewallet.cpp
  src/wallet/wallet2.cpp
  src/wallet/wallet2.h
  src/wallet/wallet_errors.h
  src/wallet/wallet_rpc_server.cpp
  src/wallet/wallet_rpc_server.h
  src/wallet/wallet_rpc_server_commands_defs.h
  tests/functional_tests/transfer.py
  tests/unit_tests/epee_utils.cpp
  utils/python-rpc/framework/wallet.py
Labels: pending review, feature, important, allarch, wallet

#9008 wallet2: add on_reorg callback [release]
  src/wallet/wallet2.cpp
  src/wallet/wallet2.h
Labels: allarch

#9121 depends: update config scripts
  contrib/depends/config.guess
  contrib/depends/config.sub
Labels: enhancement, easy

#9125 epee/test: remove levin_protocol_handler and core_proxy tests
  contrib/epee/include/net/levin_protocol_handler.h
  src/p2p/net_node.h
  tests/CMakeLists.txt
  tests/core_proxy/CMakeLists.txt
  tests/core_proxy/core_proxy.cpp
  tests/core_proxy/core_proxy.h
Labels: easy

#9128 actions: remove unnecessary packages
  .github/workflows/build.yml
Labels: enhancement

#9130 wallet: mitigate statistical dependence for decoy selection within rings [RELEASE]
  src/wallet/wallet2.cpp
Labels: enhancement

#9132 Cleanup extra memory allocation, and port boost to std shared_ptr
  contrib/epee/include/misc_language.h
Labels: enhancement, low priority

#9138 Disable/fix ports with I2P
  src/net/i2p_address.cpp
  src/net/i2p_address.h
  src/net/parse.cpp
  src/p2p/net_peerlist_boost_serialization.h
  tests/unit_tests/net.cpp
Labels: pending review, networking

#9142 Disable/fix ports with I2P [0.18]
  src/net/i2p_address.cpp
  src/net/i2p_address.h
  src/net/parse.cpp
  src/p2p/net_peerlist_boost_serialization.h
  tests/unit_tests/net.cpp
Labels: pending review, networking

#9145 Add <cstdint> to aligned test
  tests/unit_tests/aligned.cpp
Labels: easy

#9156 Zero initialize rctSigBase elements
  src/ringct/rctTypes.h
Labels: low priority

#9159 remove ARCH="x86-64" from release-static [RELEASE]
  Makefile
Labels: enhancement, build system

#9160 Daemon-specific proxy for the wallet-rpc.
  src/wallet/wallet2.cpp
  src/wallet/wallet2.h
  src/wallet/wallet_rpc_server.cpp
  src/wallet/wallet_rpc_server_commands_defs.h
  src/wallet/wallet_rpc_server_error_codes.h
Labels: pending review, feature, low priority, wallet

#9163 depends: unbound: update to 1.19.1
  contrib/depends/funcs.mk
  contrib/depends/packages/unbound.mk
Labels: enhancement, build system

#9164 depends: expat: update to 2.6.0
  contrib/depends/packages/expat.mk
Labels: enhancement, build system

#9165 depends: openssl: update to 3.0.13
  contrib/depends/packages/openssl.mk
Labels: enhancement, build system

#9178 depends: update expat, unbound, openssl [RELEASE]
  contrib/depends/funcs.mk
  contrib/depends/packages/expat.mk
  contrib/depends/packages/openssl.mk
  contrib/depends/packages/unbound.mk
Labels: enhancement, build system

#9182 depends: android_ndk: update to 18b
  contrib/depends/packages/android_ndk.mk
  contrib/depends/patches/android_ndk/api_definition.patch
Labels: enhancement, build system

#9188 cryptonote_core: early out on out of bounds scaling parameter [release-v0.18]
  src/cryptonote_core/blockchain.cpp
Labels: enhancement

#9189 cryptonote_core: early out on out of bounds scaling parameter
  src/cryptonote_core/blockchain.cpp
Labels: enhancement

#9190 docs: omit i2p port number from ANONYMITY_NETWORKS [release-v0.18]
  docs/ANONYMITY_NETWORKS.md
Labels: documentation

#9191 docs: omit i2p port number from ANONYMITY_NETWORKS
  docs/ANONYMITY_NETWORKS.md
Labels: documentation

#9136 build: prepare v0.18.3.2
  README.md
  contrib/gitian/DOCKRUN.md
  contrib/gitian/README.md
  src/blocks/checkpoints.dat
  src/checkpoints/checkpoints.cpp
  src/cryptonote_core/blockchain.cpp
  src/version.cpp.in
Labels: easy

#9158 serialization: fix infinite loops and clean up dispatching [RELEASE]
  src/cryptonote_basic/tx_extra.h
  src/serialization/container.h
  src/serialization/debug_archive.h
  src/serialization/difficulty_type.h
  src/serialization/pair.h
  src/serialization/serialization.h
  src/serialization/tuple.h
  src/serialization/variant.h
  tests/unit_tests/serialization.cpp
Labels: enhancement

#9004 cmake: require sodium
  CMakeLists.txt
  cmake/FindSodium.cmake
  contrib/depends/packages/packages.mk
  src/crypto/CMakeLists.txt
  src/device_trezor/CMakeLists.txt
Labels: pending review, low priority, cmake
