Repository monero-project/monero, pull requests merged in 2024-12, with the labels that each got.

#8929 Bootstrappable Builds
  .github/workflows/gitian.yml
  .github/workflows/guix.yml
  .gitignore
  CMakeLists.txt
  README.md
  contrib/depends/Makefile
  contrib/depends/funcs.mk
  contrib/depends/hosts/darwin.mk
  contrib/depends/hosts/freebsd.mk
  contrib/depends/hosts/linux.mk
  contrib/depends/packages/android_ndk.mk
  contrib/depends/packages/boost.mk
  contrib/depends/packages/darwin_sdk.mk
  contrib/depends/packages/freebsd_base.mk
  contrib/depends/packages/native_cctools.mk
  contrib/depends/packages/native_clang.mk
  contrib/depends/packages/native_libtapi.mk
  contrib/depends/packages/packages.mk
  contrib/depends/patches/android_ndk/fix_env.patch
  contrib/depends/patches/boost/fix_coalesce.patch
  contrib/depends/toolchain.cmake.in
  contrib/gitian/DOCKRUN.md
  contrib/gitian/README.md
  contrib/gitian/dockrun.sh
  contrib/gitian/gitian-android.yml
  contrib/gitian/gitian-build.py
  contrib/gitian/gitian-freebsd.yml
  contrib/gitian/gitian-linux.yml
  contrib/gitian/gitian-osx.yml
  contrib/gitian/gitian-win.yml
  contrib/guix/INSTALL.md
  contrib/guix/README.md
  contrib/guix/guix-attest
  contrib/guix/guix-build
  contrib/guix/guix-clean
  contrib/guix/guix-verify
  contrib/guix/libexec/build.sh
  contrib/guix/libexec/prelude.bash
  contrib/guix/manifest.scm
  contrib/guix/patches/gcc-remap-guix-store.patch
  contrib/guix/patches/glibc-2.27-guix-prefix.patch
  contrib/guix/patches/glibc-2.27-no-librt.patch
  contrib/guix/patches/glibc-2.27-riscv64-Use-__has_include-to-include-asm-syscalls.h.patch
  contrib/guix/patches/winpthreads-remap-guix-store.patch
  contrib/shell/git-utils.bash
  docs/RELEASE_CHECKLIST.md
Labels: build system

#9122 cryptonote_basic: faster and more readable is_valid_decomposed_amount
  src/cryptonote_basic/cryptonote_format_utils.cpp
  tests/performance_tests/is_valid_decomposed_amount.h
  tests/performance_tests/main.cpp
Labels: enhancement

#9172 variant: visit lambda and value-initialize by index
  src/common/variant.h
  tests/unit_tests/variant.cpp
Labels: enhancement

#9176 variant: split into variant and optional_variant
  src/common/variant.h
  tests/unit_tests/variant.cpp
Labels: enhancement

#9290 Fix lmdb txn commit code
  src/lmdb/database.cpp
  src/lmdb/database.h
Labels: enhancement, pending review

#9376 tx_pool: update internal data structure to boost::bimap.
  src/cryptonote_core/tx_pool.cpp
  src/cryptonote_core/tx_pool.h
Labels: enhancement, daemon

#9380 wallet2: move wallet error on RPC resp handling to wallet_errors file
  src/wallet/wallet2.cpp
  src/wallet/wallet2.h
  src/wallet/wallet_errors.h
Labels: wallet

#9381 Daemon RPC: add max_block_count field to /getblocks.bin
  src/rpc/core_rpc_server.cpp
  src/rpc/core_rpc_server_commands_defs.h
  src/rpc/daemon_messages.h
Labels: daemon

#9395 Blockchain: fix temp fails causing alt blocks to be permanently invalid
  src/cryptonote_core/blockchain.cpp
Labels: enhancement, pending review, easy, daemon

#9400 Blockchain: fix temp fails causing alt blocks to be permanently invalid [RELEASE]
  src/cryptonote_core/blockchain.cpp
Labels: daemon

#9441 blockchain: more opportunities for caching the rolling median
  src/cryptonote_core/blockchain.cpp
Labels: daemon

#9445 cmake: fix readline find_path call.
  cmake/FindReadline.cmake
Labels: low priority, easy, build system

#9451 docs: clarify proper PR title format
  docs/CONTRIBUTING.md
Labels: documentation

#9452 depends: allow granular stage env config
  contrib/depends/funcs.mk
Labels: build system

#9454 readme: add missing ubuntu/debian build tools
  README.md
Labels: documentation

#9457 depends: release type should be lower case
  contrib/depends/Makefile
Labels: easy, build system

#9469 ci: remove obsolete sdk cache
  .github/workflows/depends.yml
Labels: mac, ci

#9475 set USE_UNWIND for FreeBSD
  src/common/stack_trace.cpp
Labels: easy, bsd, build system

#9490 wallet: can't decrypt payment id if tx key is missing
  src/wallet/wallet2.cpp
Labels: wallet

#9501 depends: remove option from toolchain file
  contrib/depends/toolchain.cmake.in
Labels: enhancement, build system

#9502 depends: remove unwind from toolchain
  contrib/depends/toolchain.cmake.in
Labels: build system

#9504 fix zmq and sodium include dirs search
  CMakeLists.txt
Labels: low priority, build system

#9505 crypto: remove unused OAES code
  src/crypto/oaes_config.h
  src/crypto/oaes_lib.c
  src/crypto/oaes_lib.h
Labels: enhancement, easy

#9506 wallet2: fix error throw if unable to load cache [RELEASE]
  src/wallet/wallet2.cpp
Labels: enhancement, easy

#9507 tests: include <iomanip> where using std::setfill
  tests/trezor/trezor_tests.cpp
  tests/unit_tests/epee_utils.cpp
  tests/unit_tests/memwipe.cpp
Labels: easy, tests

#9511 Relax static_asserts in src/lmdb
  src/lmdb/key_stream.h
  src/lmdb/table.h
  src/lmdb/util.h
  src/lmdb/value_stream.h
Labels: database

#9512 Update/lmdb static asserts [0.18]
  src/lmdb/key_stream.h
  src/lmdb/table.h
  src/lmdb/util.h
  src/lmdb/value_stream.h
Labels: database

#9515 Replace deprecated result_of with decltype
  src/lmdb/database.h
Labels: database

#9518 packages: add freebsd base mirror
  contrib/depends/packages/freebsd_base.mk
Labels: build system

#9525 tests: remove unlock_time argument from trezor_tests
  tests/trezor/trezor_tests.cpp
Labels: easy, tests

#9529 tests: remove python2 compatibility
  tests/block_weight/block_weight.py
  tests/block_weight/compare.py
  tests/difficulty/gen_wide_data.py
  tests/difficulty/generate-data
  tests/difficulty/wide_difficulty.py
  tests/functional_tests/address_book.py
  tests/functional_tests/bans.py
  tests/functional_tests/blockchain.py
  tests/functional_tests/check_missing_rpc_methods.py
  tests/functional_tests/cold_signing.py
  tests/functional_tests/daemon_info.py
  tests/functional_tests/functional_tests_rpc.py
  tests/functional_tests/get_output_distribution.py
  tests/functional_tests/integrated_address.py
  tests/functional_tests/k_anonymity.py
  tests/functional_tests/mining.py
  tests/functional_tests/multisig.py
  tests/functional_tests/p2p.py
  tests/functional_tests/proofs.py
  tests/functional_tests/rpc_payment.py
  tests/functional_tests/sign_message.py
  tests/functional_tests/speed.py
  tests/functional_tests/transfer.py
  tests/functional_tests/txpool.py
  tests/functional_tests/uri.py
  tests/functional_tests/util_resources.py
  tests/functional_tests/validate_address.py
  tests/functional_tests/wallet.py
Labels: easy, tests

#9530 Add byte_stream `value_type` and `data()` [0.18]
  contrib/epee/include/byte_stream.h
Labels: easy

#9531 readme: fix win64 cross-compile requirements
  README.md
Labels: documentation

#9532 ci: cleanup depends package requirements
  .github/workflows/depends.yml
Labels: ci

#9533 readme: remove outdated gtest note
  README.md
Labels: documentation

#9535 readme: update msys2 build instructions
  README.md
Labels: documentation

#9536 build: remove unneeded cmake toolchain files
  Makefile
  cmake/32-bit-toolchain.cmake
  cmake/64-bit-toolchain.cmake
Labels: build system

#9537 readme: update raspberry pi build instructions
  README.md
Labels: documentation

#9540 brew: remove unneeded taps
  contrib/brew/Brewfile
Labels: documentation

#9541 cmake: lowercase ARCH_ID
  CMakeLists.txt
Labels: build system

#9543 cmake: make PER_BLOCK_CHECKPOINT an option
  CMakeLists.txt
  src/blockchain_utilities/CMakeLists.txt
  src/daemon/CMakeLists.txt
  src/device/CMakeLists.txt
Labels: build system

#9548 wallet2_api: use `std::optional` instead of handmade `optional`
  src/wallet/api/wallet2_api.h
Labels: enhancement, wallet

#9549 Update PORTABLE_STORAGE.md
  docs/PORTABLE_STORAGE.md
Labels: low priority, documentation

#9554 monerod.service: use network-online.target [RELEASE]
  utils/systemd/monerod.service
Labels: easy

#9556 ringct: add operator!= for `key`
  src/ringct/rctTypes.h
Labels: easy

#9560 serialization: silence warning about shifting `uint8_t` by 8
  src/serialization/binary_archive.h
Labels: easy

#9565 Fix typos.
  src/device_trezor/device_trezor.cpp
  src/multisig/multisig_account.h
  src/multisig/multisig_account_kex_impl.cpp
  src/wallet/wallet2.cpp
Labels: easy

#9574 contrib: force (de)serialization to create params section incase there is none.
  contrib/epee/include/net/http_server_handlers_map2.h
  tests/unit_tests/epee_serialization.cpp
Labels: important, easy, networking

#9577 gpg_keys: bump my key's expiration date by another five years
  utils/gpg_keys/moneromooo.asc
Labels: pending review, easy

#9580 add SNeedlewoods gpg key
  utils/gpg_keys/SNeedlewoods.asc
Labels: easy

#9581 wallet: report exact reason for open_wallet failure.
  src/wallet/wallet_rpc_server.cpp
Labels: easy, wallet

#9583 Fix memcpy in byte_slice constructor
  contrib/epee/src/byte_slice.cpp
Labels: easy

#9584 Fix memcpy in byte_slice constructor [0.18]
  contrib/epee/src/byte_slice.cpp
Labels: easy

#9585 Replace in-tree MD5 with OpenSSL
  contrib/epee/include/md5_l.h
  contrib/epee/include/md5_l.inl
  contrib/epee/include/md5global.h
  contrib/epee/src/http_auth.cpp
  tests/unit_tests/http.cpp
Labels: critical, easy

#9589 Fixes tar extract cmd for systems with 16 bit uid_t
  contrib/depends/funcs.mk
Labels: low priority, easy

#9590 wallet2: daemon-specific proxy for the wallet-rpc [release]
  src/wallet/wallet2.cpp
  src/wallet/wallet2.h
  src/wallet/wallet_rpc_server.cpp
  src/wallet/wallet_rpc_server_commands_defs.h
Labels: easy, wallet

#9592 simplewallet: add header to show_transfers command
  src/simplewallet/simplewallet.cpp
Labels: easy, wallet

#9593 Keys: 2nd update for expired 'brunner7' key, valid 2 years
  utils/gpg_keys/rbrunner7.asc
Labels: easy

#9607 epee: partially revert string tools to fix linking errors [RELEASE]
  contrib/epee/include/string_tools.h
  contrib/epee/src/readline_buffer.cpp
  contrib/epee/src/string_tools.cpp
Labels: easy

#9614 wallet: report exact reason for open_wallet failure [RELEASE]
  src/wallet/wallet_rpc_server.cpp
Labels: easy, wallet

#9615 contrib: force (de)serialization to create params section incase there is none [RELEASE]
  contrib/epee/include/net/http_server_handlers_map2.h
  tests/unit_tests/epee_serialization.cpp
Labels: networking

#9616 p2p: allow comments in banlist files [RELEASE]
  src/daemon/command_parser_executor.cpp
  src/p2p/net_node.inl
  tests/data/node/banlist_1.txt
  tests/unit_tests/node_server.cpp
Labels: daemon

#9623 ci: msys2: pin boost to 1.86.0
  .github/workflows/build.yml
Labels: ci

#9624 ci: msys2: pin boost to 1.86.0 [RELEASE]
  .github/workflows/build.yml
Labels: ci

#9625 ci: brew: pin boost to 1.85
  .github/workflows/build.yml
  contrib/brew/Brewfile
Labels: ci

#9626 ci: brew: pin boost to 1.85 [RELEASE]
  .github/workflows/build.yml
  contrib/brew/Brewfile
Labels: ci

#9629 ci: don't fail-fast on matrix jobs
  .github/workflows/build.yml
Labels: ci

#9542 cmake: use pkgconfig to find zeromq
  .github/workflows/build.yml
  CMakeLists.txt
  README.md
  contrib/depends/toolchain.cmake.in
  src/daemon/CMakeLists.txt
  src/net/CMakeLists.txt
  src/rpc/CMakeLists.txt
  tests/trezor/CMakeLists.txt
  tests/unit_tests/CMakeLists.txt
Labels: build system
