Repository monero-project/monero, pull requests merged in 2024-08, with the labels that each got.

#9357 Add MacOS Arm artifact output
  .github/workflows/depends.yml
Labels: enhancement, low priority

#9384 Fix ZMQ DaemonInfo
  src/rpc/daemon_handler.cpp
  src/rpc/message_data_structs.h
  src/serialization/json_object.cpp
  tests/unit_tests/json_serialization.cpp
Labels: pending review, daemon

#9385 Fix ZMQ DaemonInfo [0.18 release]
  src/rpc/daemon_handler.cpp
  src/rpc/message_data_structs.h
  src/serialization/json_object.cpp
  tests/unit_tests/json_serialization.cpp
Labels: pending review, daemon

#9421 monerod.service: use network-online.target
  utils/systemd/monerod.service
Labels: easy

#9425 Make wallet2::estimate_fee static
  src/wallet/wallet2.cpp
  src/wallet/wallet2.h
Labels: easy

#9426 Make wallet2::estimate_fee static [0.18]
  src/wallet/wallet2.cpp
  src/wallet/wallet2.h
Labels: easy

#9345 build: prepare v0.18.3.4
  README.md
  contrib/gitian/DOCKRUN.md
  contrib/gitian/README.md
  src/blocks/checkpoints.dat
  src/checkpoints/checkpoints.cpp
  src/cryptonote_core/blockchain.cpp
  src/version.cpp.in
Labels: pending review, build system

#9287 serialization: support passing extra args to fields in DSL
  src/common/va_args.h
  src/serialization/serialization.h
Labels: enhancement, important

#9416 rpc: add cumul weight field to block template resp
  src/cryptonote_basic/miner.cpp
  src/cryptonote_basic/miner.h
  src/cryptonote_core/blockchain.cpp
  src/cryptonote_core/blockchain.h
  src/cryptonote_core/cryptonote_core.cpp
  src/cryptonote_core/cryptonote_core.h
  src/rpc/core_rpc_server.cpp
  src/rpc/core_rpc_server.h
  src/rpc/core_rpc_server_commands_defs.h
  tests/functional_tests/blockchain.py
Labels: daemon
