Repository monero-project/monero, pull requests merged in 2024-05, with the labels that each got.

#7852 [seraphis] wallet2: replace ambiguous 'multisig()' function with 'multisig_status' struct
  src/gen_multisig/gen_multisig.cpp
  src/multisig/multisig_account.h
  src/simplewallet/simplewallet.cpp
  src/wallet/api/wallet.cpp
  src/wallet/api/wallet2_api.h
  src/wallet/message_store.h
  src/wallet/wallet2.cpp
  src/wallet/wallet2.h
  src/wallet/wallet_rpc_server.cpp
  src/wallet/wallet_rpc_server_commands_defs.h
  tests/unit_tests/multisig.cpp
Labels: seraphis

#8488 tests: update block_weight for 2021 scaling
  tests/block_weight/block_weight.cpp
  tests/block_weight/block_weight.py
Labels: tests

#8920 [seraphis] common: update TimingsDatabase
  src/common/timings.cc
  src/common/timings.h
  tests/performance_tests/performance_tests.h
Labels: seraphis

#9064 trezor: support c++17 and protobuf v25, libusb fix #smol
  cmake/CheckTrezor.cmake
  cmake/FindLibUSB.cmake
  src/device_trezor/README.md
  tests/core_tests/wallet_tools.h
  tests/trezor/trezor_tests.cpp
Labels: cmake, documentation, allarch

#9149 epee: cleanup string_tools
  contrib/epee/include/string_tools.h
  contrib/epee/src/readline_buffer.cpp
  contrib/epee/src/string_tools.cpp
Labels: pending review, low priority

#9151 Enforce Tx unlock_time is Zero by Relay Rule
  src/cryptonote_basic/verification_context.h
  src/cryptonote_core/cryptonote_tx_utils.cpp
  src/cryptonote_core/cryptonote_tx_utils.h
  src/cryptonote_core/tx_pool.cpp
  src/multisig/multisig_tx_builder_ringct.cpp
  src/multisig/multisig_tx_builder_ringct.h
  src/rpc/core_rpc_server.cpp
  src/rpc/core_rpc_server_commands_defs.h
  src/rpc/daemon_handler.cpp
  src/simplewallet/simplewallet.cpp
  src/simplewallet/simplewallet.h
  src/wallet/api/wallet.cpp
  src/wallet/wallet2.cpp
  src/wallet/wallet2.h
  src/wallet/wallet_errors.h
  src/wallet/wallet_rpc_server.cpp
  src/wallet/wallet_rpc_server_error_codes.h
  tests/core_tests/block_validation.cpp
  tests/core_tests/bulletproof_plus.cpp
  tests/core_tests/bulletproofs.cpp
  tests/core_tests/chaingen.cpp
  tests/core_tests/chaingen.h
  tests/core_tests/double_spend.inl
  tests/core_tests/integer_overflow.cpp
  tests/core_tests/multisig.cpp
  tests/core_tests/rct.cpp
  tests/core_tests/rct2.cpp
  tests/core_tests/transaction_tests.cpp
  tests/core_tests/tx_validation.cpp
  tests/core_tests/v2_tests.cpp
  tests/core_tests/wallet_tools.cpp
  tests/core_tests/wallet_tools.h
  tests/functional_tests/transactions_flow_test.cpp
  tests/performance_tests/check_tx_signature.h
  tests/performance_tests/construct_tx.h
  tests/performance_tests/ge_frombytes_vartime.h
  tests/performance_tests/ge_tobytes.h
  tests/unit_tests/json_serialization.cpp
Labels: pending review, important

#9194 serialization: protect blob serialization from undefined behavior
  src/ringct/rctTypes.h
  src/serialization/crypto.h
  src/serialization/serialization.h
  tests/unit_tests/serialization.cpp
Labels: enhancement

#9198 [seraphis] crypto: add blake2b
  src/crypto/CMakeLists.txt
  src/crypto/blake2b.c
  src/crypto/blake2b.h
  tests/hash/main.cpp
Labels: enhancement, pending review, seraphis

#9199 depends: {native_,}protobuf: speedup build
  Makefile
  contrib/depends/packages/native_protobuf.mk
  contrib/depends/packages/protobuf.mk
Labels: build system

#9200 depends: native_cctools: don't embed build date
  contrib/depends/packages/native_cctools.mk
  contrib/depends/patches/native_cctools/no-build-date.patch
Labels: build system

#9204 depends: native_libtapi: don't embed git hash
  contrib/depends/packages/native_libtapi.mk
  contrib/depends/patches/native_libtapi/no_embed_git_rev.patch
Labels: build system

#9205 depends: fix ar zero timestamp for openssl & unbound on android targets
  contrib/depends/packages/openssl.mk
  contrib/depends/packages/unbound.mk
Labels: build system

#9211 monero-wallet-rpc - Changed default cryptonote port
  src/wallet/wallet2.cpp
  src/wallet/wallet2.h
Labels: pending review, low priority, wallet

#9232 Blockchain: remove old fee calc logic
  src/cryptonote_core/blockchain.cpp
  src/cryptonote_core/blockchain.h
  src/rpc/core_rpc_server.cpp
  src/rpc/daemon_handler.cpp
  tests/unit_tests/CMakeLists.txt
  tests/unit_tests/fee.cpp
  tests/unit_tests/scaling_2021.cpp
Labels: easy, tests

#9245 functional_tests: test HTTP digest authentication
  tests/functional_tests/functional_tests_rpc.py
  tests/functional_tests/http_digest_auth.py
  utils/python-rpc/framework/daemon.py
  utils/python-rpc/framework/rpc.py
  utils/python-rpc/framework/wallet.py
Labels: tests

#9254 epee: cleanup string_tools [RELEASE]
  contrib/epee/include/string_tools.h
  contrib/epee/src/readline_buffer.cpp
  contrib/epee/src/string_tools.cpp
Labels: pending review

#9257 serialization: do any N-tuple
  src/serialization/tuple.h
  tests/unit_tests/serialization.cpp
Labels: enhancement

#9259 wallet2: ensure transfers and sweeps use same fee calc logic rnd2
  src/wallet/wallet2.cpp
Labels: wallet

#9260 wallet2: ensure transfers and sweeps use same fee calc logic rnd2 [release]
  src/wallet/wallet2.cpp
Labels: wallet

#9267 Skip privacy networks (on tx sends) that don't have outgoing connections [0.18]
  src/cryptonote_protocol/levin_notify.cpp
  src/cryptonote_protocol/levin_notify.h
  src/p2p/net_node.inl
  tests/unit_tests/levin.cpp
Labels: daemon

#9268 Skip privacy networks (on tx sends) that don't have outgoing connections
  src/cryptonote_protocol/levin_notify.cpp
  src/cryptonote_protocol/levin_notify.h
  src/p2p/net_node.inl
  tests/unit_tests/levin.cpp
Labels: daemon

#9270 common: fix privatefile create.
  src/common/util.cpp
  src/common/util.h
  src/wallet/wallet_rpc_server.cpp
Labels: easy

#9282 src: update checkpoints to match latest release
  src/blocks/checkpoints.dat
  src/checkpoints/checkpoints.cpp
  src/cryptonote_core/blockchain.cpp
Labels: daemon

#9291 build: force Trezor for depends builds [release]
  Makefile
Labels: build system

#9292 common: fix privatefile create [RELEASE]
  src/common/util.cpp
  src/common/util.h
  src/wallet/wallet_rpc_server.cpp
Labels: easy

#9305 common: support boost filesystem copy_options.
  src/common/util.cpp
  src/common/util.h
  src/p2p/net_peerlist.cpp
  src/wallet/wallet2.cpp
  tests/core_tests/chaingen_serialization.h
  tests/unit_tests/wallet_storage.cpp
Labels: pending review, low priority, easy

#9306 common: support boost filesystem copy_options. [RELEASE]
  src/common/boost_serialization_helper.h
  src/common/util.cpp
  src/common/util.h
  src/p2p/net_peerlist.cpp
  src/wallet/wallet2.cpp
  tests/unit_tests/wallet_storage.cpp
Labels: low priority, easy

#9307 simplewallet: change boost::filesystem::complete to absolute.
  src/simplewallet/simplewallet.cpp
Labels: low priority, easy

#9309 wallet2: fix stagenet get_approximate_blockchain_height [release-v0.18]
  src/wallet/wallet2.cpp
Labels: pending review, wallet

#9310 wallet2: fix stagenet get_approximate_blockchain_height
  src/wallet/wallet2.cpp
Labels: pending review, wallet

#9313 contrib: fix compilation error for boost 1.85
  contrib/epee/include/storages/portable_storage_val_converters.h
Labels: easy

#9316 net_node: update seed nodes
  src/p2p/net_node.inl
Labels: easy, daemon

#9323 net_node: update seed nodes [release-v0.18]
  src/p2p/net_node.inl
Labels: easy, daemon

#9202 depends: add command to print variables
  contrib/depends/Makefile
Labels: build system
