Repository monero-project/monero, pull requests merged in 2025-02, with the labels that each got.

#9766 ci: update to v4 actions [RELEASE]
  .github/workflows/build.yml
  .github/workflows/depends.yml
  .github/workflows/gitian.yml
Labels: ci

#9739 wallet: mark wallet error throwing functions as noreturn
  src/wallet/wallet_errors.h
Labels: wallet

#9713 guix: update documentation
  contrib/guix/README.md
Labels: documentation

#9706 ci: build wallet_api for all linux cli jobs
  .github/workflows/build.yml
Labels: ci

#9467 guix: bump time-machine to 9d09b0cf841fb657a1aec12e9bab68e00c2b493c
  contrib/guix/libexec/prelude.bash
  contrib/guix/manifest.scm
  contrib/guix/patches/glibc-2.27-riscv64-fix-incorrect-jal-with-HIDDEN_JUMPTARGET.patch
Labels: pending review, build system

#9675 depends: remove eudev
  cmake/FindHIDAPI.cmake
  cmake/FindLibUSB.cmake
  contrib/depends/packages/eudev.mk
  contrib/depends/packages/hidapi.mk
  contrib/depends/packages/packages.mk
  contrib/guix/manifest.scm
Labels: build system

#9681 depends: remove expat
  contrib/depends/packages/expat.mk
  contrib/depends/packages/packages.mk
  contrib/depends/packages/unbound.mk
  contrib/depends/patches/unbound/no-expat.patch
Labels: build system

#9724 cmake: remove obsolete msys2 workaround
  CMakeLists.txt
Labels: build system

#9725 cmake: don't explicitely link libatomic
  CMakeLists.txt
Labels: build system

#9726 cmake: remove obsolete policy setting
  CMakeLists.txt
Labels: build system

#9708 ci: containerize ubuntu cli jobs
  .github/workflows/build.yml
Labels: ci

#9792 p2p/net_node.inl : update seed node
  src/p2p/net_node.inl
Labels: daemon

#9793 p2p/net_node.inl : update seed node [release v0.18]
  src/p2p/net_node.inl
Labels: daemon

#9778 ci: containerize depends jobs [0.18]
  .github/workflows/depends.yml
Labels: ci

#9777 ci: development build backports [0.18]
  .github/actions/set-make-job-count/action.yml
  .github/workflows/build.yml
  tests/create_test_disks.sh
  tests/unit_tests/is_hdd.cpp
Labels: ci

#9771 src: bump network speed 4x [RELEASE]
  src/cryptonote_config.h
  utils/fish/monerod.fish
Labels: daemon

#9769 ci: run guix builds on Cargo.lock update
  .github/workflows/guix.yml
Labels: ci, fcmp++

#9763 tests: Improve functional_tests_rpc startup
  tests/functional_tests/functional_tests_rpc.py
Labels: tests

#9761 utils: Simplify python RPC Response implementation
  utils/python-rpc/framework/rpc.py
  utils/python-rpc/framework/test_rpc.py
Labels: tests, cleanup

#9760 ringct: remove inclusion of cryptonote_format_utils.h in rctOps.cpp
  src/ringct/rctOps.cpp
Labels: cleanup

#9759 Some cleanup in span/connection_context + few more checks [0.18]
  src/cryptonote_basic/connection_context.cpp
  src/cryptonote_basic/connection_context.h
  src/cryptonote_protocol/block_queue.cpp
  src/cryptonote_protocol/block_queue.h
  src/cryptonote_protocol/cryptonote_protocol_handler.h
  src/cryptonote_protocol/cryptonote_protocol_handler.inl
Labels: daemon

#9582 Some cleanup in span/connection_context + few more checks
  src/cryptonote_basic/connection_context.cpp
  src/cryptonote_basic/connection_context.h
  src/cryptonote_protocol/block_queue.cpp
  src/cryptonote_protocol/block_queue.h
  src/cryptonote_protocol/cryptonote_protocol_handler.h
  src/cryptonote_protocol/cryptonote_protocol_handler.inl
Labels: daemon

#9717 ringct: remove unused range proof types and fix serialization bug
  src/device_trezor/trezor/protocol.cpp
  src/ringct/rctSigs.cpp
  src/ringct/rctTypes.h
  src/wallet/wallet2.h
  tests/core_tests/bulletproof_plus.cpp
  tests/core_tests/bulletproof_plus.h
  tests/core_tests/bulletproofs.cpp
  tests/core_tests/bulletproofs.h
  tests/core_tests/chaingen_main.cpp
  tests/performance_tests/check_tx_signature.h
  tests/performance_tests/main.cpp
  tests/unit_tests/json_serialization.cpp
Labels: wallet, bugfix, cleanup

#9718 wallet: fix signed_tx_set RangeProofType serialization [RELEASE]
  src/wallet/wallet2.h
Labels: wallet, bugfix

#9687 depends: boost: update to 1.66.0 [RELEASE]
  CMakeLists.txt
  contrib/depends/packages/boost.mk
Labels: build system

#9711 brew: use latest protobuf
  .github/workflows/build.yml
  contrib/brew/Brewfile
  src/device_trezor/README.md
Labels: documentation, ci

#9456 depends: android_ndk: update to 27 (latest LTS)
  contrib/depends/hosts/android.mk
  contrib/depends/packages/android_ndk.mk
  contrib/depends/packages/openssl.mk
  contrib/depends/patches/android_ndk/api_definition.patch
  contrib/depends/patches/android_ndk/fix_env.patch
  contrib/depends/patches/openssl/fix-android.patch
  contrib/depends/toolchain.cmake.in
Labels: build system

#9773 depends: use staging_prefix_dir where possible
  contrib/depends/packages/darwin_sdk.mk
  contrib/depends/packages/freebsd_base.mk
Labels: build system, cleanup

#9654 guix: remove automake & autoconf
  contrib/guix/manifest.scm
Labels: build system

#9671 depends: always pass --with-pic to autoconf builds
  contrib/depends/funcs.mk
  contrib/depends/packages/libusb.mk
  contrib/depends/packages/unbound.mk
  contrib/depends/packages/zeromq.mk
Labels: build system

#9762 tests: Improve p2p tx propagation functional test
  tests/functional_tests/p2p.py
Labels: tests

#9728 cmake: remove redundant config env var
  CMakeLists.txt
Labels: build system

#9765 Add configuration options to HTTP server
  contrib/epee/include/net/abstract_tcp_server2.h
  contrib/epee/include/net/abstract_tcp_server2.inl
  contrib/epee/include/net/http_protocol_handler.h
  contrib/epee/include/net/http_protocol_handler.inl
  contrib/epee/include/net/http_server_impl_base.h
  src/cryptonote_config.h
  src/p2p/net_node.cpp
  src/rpc/core_rpc_server.cpp
  src/rpc/core_rpc_server.h
  src/wallet/wallet_rpc_server.cpp
  tests/functional_tests/functional_tests_rpc.py
  tests/unit_tests/CMakeLists.txt
  tests/unit_tests/epee_http_server.cpp
Labels: networking

#9775 Set response limits on http server connections [0.18]
  contrib/epee/include/net/abstract_tcp_server2.h
  contrib/epee/include/net/abstract_tcp_server2.inl
  contrib/epee/include/net/http_protocol_handler.h
  contrib/epee/include/net/http_protocol_handler.inl
  contrib/epee/include/net/http_server_handlers_map2.h
  contrib/epee/include/net/http_server_impl_base.h
  src/cryptonote_config.h
  src/daemon/main.cpp
  src/daemon/rpc_command_executor.cpp
  src/p2p/net_node.cpp
  src/rpc/core_rpc_server.cpp
  src/rpc/core_rpc_server.h
  src/wallet/wallet_rpc_server.cpp
  tests/functional_tests/functional_tests_rpc.py
  tests/unit_tests/CMakeLists.txt
  tests/unit_tests/epee_http_server.cpp
Labels: networking

#9800 Fix build with boost ASIO 1.87. Support boost 1.66+ [0.18]
  .github/workflows/build.yml
  README.md
  contrib/brew/Brewfile
  contrib/epee/include/net/abstract_tcp_server2.h
  contrib/epee/include/net/abstract_tcp_server2.inl
  contrib/epee/include/net/connection_basic.hpp
  contrib/epee/include/net/http_server_impl_base.h
  contrib/epee/include/net/levin_protocol_handler_async.h
  contrib/epee/include/net/net_helper.h
  contrib/epee/include/net/net_ssl.h
  contrib/epee/include/net/net_utils_base.h
  contrib/epee/src/connection_basic.cpp
  contrib/epee/src/net_helper.cpp
  contrib/epee/src/net_ssl.cpp
  src/common/util.cpp
  src/cryptonote_core/blockchain.cpp
  src/cryptonote_core/blockchain.h
  src/cryptonote_protocol/levin_notify.cpp
  src/cryptonote_protocol/levin_notify.h
  src/device_trezor/trezor/transport.cpp
  src/device_trezor/trezor/transport.hpp
  src/net/parse.cpp
  src/net/socks.cpp
  src/net/socks.h
  src/net/socks_connect.cpp
  src/p2p/net_node.cpp
  src/p2p/net_node.h
  src/p2p/net_node.inl
  src/rpc/rpc_args.cpp
  tests/fuzz/levin.cpp
  tests/net_load_tests/net_load_tests.h
  tests/net_load_tests/srv.cpp
  tests/unit_tests/epee_boosted_tcp_server.cpp
  tests/unit_tests/epee_levin_protocol_handler_async.cpp
  tests/unit_tests/levin.cpp
  tests/unit_tests/net.cpp
  tests/unit_tests/node_server.cpp
Labels: build system

#9787 wallet: add wallet rpc call to get default fee priority
  src/wallet/wallet_rpc_server.cpp
  src/wallet/wallet_rpc_server.h
  src/wallet/wallet_rpc_server_commands_defs.h
  utils/python-rpc/framework/wallet.py
Labels: wallet

#9788 wallet: add wallet rpc call to get default fee priority [RELEASE]
  src/wallet/wallet_rpc_server.cpp
  src/wallet/wallet_rpc_server.h
  src/wallet/wallet_rpc_server_commands_defs.h
  utils/python-rpc/framework/wallet.py
Labels: wallet

#9797 ci: add arch linux build [0.18]
  .github/workflows/build.yml
Labels: ci

#9784 ci: containerize depends jobs
  .github/workflows/depends.yml
  .github/workflows/guix.yml
  contrib/depends/packages/hidapi.mk
  contrib/depends/packages/native_cctools.mk
  contrib/depends/packages/ncurses.mk
  contrib/depends/packages/readline.mk
  contrib/depends/packages/sodium.mk
  contrib/depends/packages/zeromq.mk
  contrib/depends/toolchain.cmake.in
  contrib/guix/README.md
  contrib/guix/guix-build
Labels: ci

#9428 contrib: smaller and more reasonable log size.
  contrib/epee/include/misc_log_ex.h
Labels: low priority, easy

#9439 assign default port for http and https
  contrib/epee/src/abstract_http_client.cpp
Labels: easy, networking

#9438 assign default port for http and https [RELEASE]
  contrib/epee/src/abstract_http_client.cpp
Labels: easy, networking

#9804 BlockchainLMDB: fix data.mdb nuking on Windows
  src/blockchain_db/lmdb/db_lmdb.cpp
Labels: database

#9805 BlockchainLMDB: fix data.mdb nuking on Windows [RELEASE]
  src/blockchain_db/lmdb/db_lmdb.cpp
Labels: database

#9538 make: remove static targets
  .github/workflows/build.yml
  Makefile
  README.md
Labels: build system
