Repository monero-project/monero, pull requests merged in 2025-01, with the labels that each got.

#9649 unit_tests: fix variant tests after 'optional' name split
  tests/unit_tests/variant.cpp
Labels: tests

#9162 depends: boost: update to 1.84.0
  contrib/depends/packages/boost.mk
  contrib/depends/patches/boost/fix_arm_arch.patch
  contrib/depends/patches/boost/fix_aroptions.patch
  contrib/depends/patches/boost/fix_coalesce.patch
Labels: enhancement, build system

#9510 CI: -j4 with lin/win runners
  .github/workflows/build.yml
  .github/workflows/depends.yml
Labels: enhancement, ci

#9601 wallet: shortchain history should include base block
  src/wallet/wallet2.cpp
Labels: important, wallet

#9602 wallet: shortchain history should include base block [RELEASE]
  src/wallet/wallet2.cpp
Labels: important, wallet

#9640 depends: add cmake config command
  contrib/depends/funcs.mk
Labels: build system

#9600 dns_util: add new DNSSEC trust anchor
  src/common/dns_utils.cpp
Labels: networking

#9621 Blockchain: get height of RingCT fork programmatically
  src/cryptonote_core/blockchain.cpp
Labels: daemon

#9622 Blockchain: get height of RingCT fork programmatically [RELEASE]
  src/cryptonote_core/blockchain.cpp
Labels: daemon

#9632 Fix --anonymous-inbound data leak
  src/p2p/net_node.inl
Labels: enhancement, daemon

#9633 Fix --anonymous-inbound data leak [0.18]
  src/p2p/net_node.inl
Labels: enhancement, daemon

#9637 CI: -j4 with lin/win runners [RELEASE]
  .github/workflows/build.yml
  .github/workflows/depends.yml
Labels: ci

#9656 common/password: flush confirm prompt before user input
  src/common/password.cpp
Labels: wallet

#9657 common/password: flush confirm prompt before user input [RELEASE]
  src/common/password.cpp
Labels: wallet

#9659 p2p: remove dead protocol defs
  src/debug_utilities/object_sizes.cpp
  src/p2p/p2p_protocol_defs.h
Labels: daemon

#9660 validate ip parameter in set_bans rpc call
  src/rpc/core_rpc_server.cpp
Labels: daemon, bugfix

#9663 Fix get_database_size on Windows
  contrib/epee/include/file_io_utils.h
  contrib/epee/src/file_io_utils.cpp
  src/blockchain_db/lmdb/db_lmdb.cpp
  src/common/download.cpp
Labels: bugfix

#9685 miniupnpc: fix build with gcc 14 [RELEASE]
  external/CMakeLists.txt
Labels: build system

#9686 miniupnpc: fix build with gcc 14
  external/CMakeLists.txt
Labels: build system

#9644 ci: print guix hashes to summary
  .github/workflows/guix.yml
Labels: ci

#9477 trezor: replace Python tools with CMake
  cmake/CheckTrezor.cmake
  src/device_trezor/trezor/tools/README.md
  src/device_trezor/trezor/tools/build_protob.py
  src/device_trezor/trezor/tools/pb2cpp.py
  src/device_trezor/trezor/tools/py2backports/__init__.py
  src/device_trezor/trezor/tools/py2backports/tempfile.py
  src/device_trezor/trezor/tools/py2backports/weakref.py
Labels: build system

#9528 guix: drop 32-bit android target
  .github/workflows/guix.yml
  contrib/guix/guix-build
Labels: arm, build system

#9470 build: drop support for 32-bit windows target
  .github/workflows/depends.yml
Labels: important, build system

#9710 tests: fix IPv4Success, DNSSECSuccess [RELEASE]
  tests/unit_tests/dns_resolver.cpp
Labels: tests

#9171 build: remove glibc backcompat
  CMakeLists.txt
  README.md
  contrib/depends/packages/sodium.mk
  contrib/depends/packages/unbound.mk
  contrib/depends/patches/sodium/disable-glibc-getrandom-getentropy.patch
  contrib/depends/patches/unbound/disable-glibc-reallocarray.patch
  src/common/CMakeLists.txt
  src/common/compat/glibc_compat.cpp
Labels: enhancement, build system

#9389 wallet2: remove refresh() from scan_tx
  src/wallet/wallet2.cpp
  tests/functional_tests/transfer.py
Labels: important, wallet

#9664 Check for windows NTFS compression on monerod startup (fixes #9617)
  src/blockchain_db/lmdb/db_lmdb.cpp
Labels: enhancement, daemon

#9702 release-v0.18: check for windows NTFS compression on database files
  src/blockchain_db/lmdb/db_lmdb.cpp
Labels: enhancement, daemon

#9703 release-v0.18: validate ip parameter in set_bans rpc call
  src/rpc/core_rpc_server.cpp
Labels: daemon, bugfix

#9705 Fix get_database_size on Windows [0.18]
  contrib/epee/include/file_io_utils.h
  contrib/epee/src/file_io_utils.cpp
  src/blockchain_db/lmdb/db_lmdb.cpp
  src/common/download.cpp
Labels: bugfix

#9683 Failed to build for FreeBSD using GCC
  src/common/stack_trace.cpp
Labels: build system

#9453 depends: freebsd_base: update to 12.3
  contrib/depends/packages/freebsd_base.mk
Labels: pending review, build system

#9544 daemonizer: replace boost chrono/thread with std lib
  src/daemonizer/CMakeLists.txt
  src/daemonizer/windows_service.cpp
Labels: easy

#9645 depends: cleanup packages.mk
  contrib/depends/packages/packages.mk
Labels: build system

#9646 depends: sodium: drop unneeded patch
  contrib/depends/packages/sodium.mk
  contrib/depends/patches/sodium/fix-whitespace.patch
Labels: build system

#9648 guix: remove p7zip
  contrib/guix/manifest.scm
Labels: build system

#9650 guix: remove moreutils
  contrib/guix/libexec/build.sh
  contrib/guix/manifest.scm
Labels: build system

#9653 depends: don't run auto(re)conf anywhere
  contrib/depends/packages/eudev.mk
  contrib/depends/packages/libusb.mk
  contrib/depends/packages/sodium.mk
  contrib/depends/packages/unbound.mk
Labels: build system

#9459 Cleanup TCP throttling code (performance)
  contrib/epee/include/net/abstract_tcp_server2.h
  contrib/epee/include/net/abstract_tcp_server2.inl
  contrib/epee/include/net/network_throttle-detail.hpp
  contrib/epee/src/network_throttle-detail.cpp
  src/p2p/net_node.h
  src/p2p/net_node.inl
  tests/unit_tests/node_server.cpp
Labels: daemon, networking

#9460 Cleanup TCP throttling code (performance) [0.18]
  contrib/epee/include/net/abstract_tcp_server2.h
  contrib/epee/include/net/abstract_tcp_server2.inl
  contrib/epee/include/net/network_throttle-detail.hpp
  contrib/epee/src/network_throttle-detail.cpp
  src/p2p/net_node.h
  src/p2p/net_node.inl
  tests/unit_tests/node_server.cpp
Labels: daemon, networking

#9523 build: bump minimum macos version to 10.15
  contrib/depends/hosts/darwin.mk
  contrib/depends/toolchain.cmake.in
Labels: build system

#9643 depends: hidapi: update to 0.14.0
  contrib/depends/packages/hidapi.mk
  contrib/depends/patches/hidapi/missing_win_include.patch
Labels: build system

#9688 Revert "blockchain: detect and log bad difficulty calculations"
  src/cryptonote_core/blockchain.cpp
Labels: daemon

#9689 Revert "blockchain: detect and log bad difficulty calculations" [release-v0.18]
  src/cryptonote_core/blockchain.cpp
Labels: daemon

#9691 crypto: make CRYPTO_DEFINE_HASH_FUNCTIONS adhere strict aliasing
  src/crypto/generic-ops.h
Labels: enhancement, cryptography

#9692 crypto: make CRYPTO_DEFINE_HASH_FUNCTIONS adhere strict aliasing [RELEASE]
  src/crypto/generic-ops.h
Labels: enhancement, cryptography

#9693 common: Remove resolved FIXME in pod-class.h
  src/common/pod-class.h
Labels: easy, cleanup

#9694 crypto: remove unused POD classes
  src/crypto/crypto.h
Labels: easy, cleanup

#9680 ci: add arch linux build
  .github/workflows/build.yml
Labels: ci

#9720 functional tests: fix race in restore wallet refresh
  tests/functional_tests/transfer.py
Labels: tests, bugfix

#9721 ci: msys2: downgrade icu to fix build [RELEASE]
  .github/workflows/build.yml
Labels: ci

#9642 depends: unbound: update to 1.22.0
  contrib/depends/packages/unbound.mk
Labels: build system

#9701 daemon: fix log message typo
  src/daemon/main.cpp
Labels: easy, cleanup

#9690 build: auto-set GitHub runner make job count
  .github/actions/set-make-job-count/action.yml
  .github/workflows/build.yml
  .github/workflows/depends.yml
Labels: pending review, ci

#9716 tests: Fix tools::is_hdd unit tests
  .github/workflows/build.yml
  tests/create_test_disks.sh
  tests/unit_tests/is_hdd.cpp
Labels: tests

#9723 ci: Parallelize Arch Linux build
  .github/workflows/build.yml
Labels: ci
