Repository monero-project/monero, pull requests merged in 2025-07, with the labels that each got.

#9966 cmake: don't redefine project [0.18]
  src/cryptonote_protocol/CMakeLists.txt
  src/p2p/CMakeLists.txt
Labels: cmake

#9956 Add check for exception in tcp accept handler
  contrib/epee/include/net/abstract_tcp_server2.inl
Labels: pending review, networking

#9955 Add check for exception in tcp accept handler
  contrib/epee/include/net/abstract_tcp_server2.inl
Labels: pending review, networking

#9948 Add is_same_host check to p2p
  src/p2p/net_node.inl
Labels: daemon

#9949 Add is_same_host check to p2p [0.18]
  src/p2p/net_node.inl
Labels: daemon

#9978 simplewallet: respect `do-not-relay` in `sweep_single` [0.18]
  src/simplewallet/simplewallet.cpp
Labels: wallet, bugfix

#9954 wallet: immediate lookahead table expansion + set_subaddresss_lookahead RPC endpoint [0.18]
  src/wallet/wallet2.cpp
  src/wallet/wallet2.h
  src/wallet/wallet_rpc_server.cpp
  src/wallet/wallet_rpc_server.h
  src/wallet/wallet_rpc_server_commands_defs.h
  tests/functional_tests/transfer.py
  tests/functional_tests/wallet.py
  tests/unit_tests/subaddress.cpp
  utils/python-rpc/framework/wallet.py
Labels: pending review, wallet

#9946 build: prepare v0.18.4.1
  README.md
  contrib/gitian/DOCKRUN.md
  contrib/gitian/README.md
  src/blocks/checkpoints.dat
  src/checkpoints/checkpoints.cpp
  src/cryptonote_core/blockchain.cpp
  src/version.cpp.in
Labels: build system

#9940 wallet: kill support for deprecated ephemeral Boost messages
  src/blockchain_utilities/blockchain_blackball.cpp
  src/blockchain_utilities/blockchain_stats.cpp
  src/blockchain_utilities/blocksdat_file.h
  src/blockchain_utilities/bootstrap_serialization.h
  src/cryptonote_core/blockchain.cpp
  src/cryptonote_core/tx_pool.cpp
  src/simplewallet/simplewallet.cpp
  src/wallet/message_store.cpp
  src/wallet/message_store.h
  src/wallet/message_transporter.h
  src/wallet/wallet2.cpp
  src/wallet/wallet2.h
  src/wallet/wallet_rpc_server.cpp
  tests/data/signed_monero_tx
  tests/data/unsigned_monero_tx
  tests/unit_tests/serialization.cpp
Labels: wallet, cleanup

#9927 tools::variant: remove
  src/common/variant.h
  src/serialization/variant.h
  tests/unit_tests/CMakeLists.txt
  tests/unit_tests/variant.cpp
Labels: cleanup

#9925 BlockchainLMDB: mark overridden methods with `override`
  src/blockchain_db/lmdb/db_lmdb.h
Labels: cleanup

#9968 ci: bump debian to 11
  .github/workflows/build.yml
Labels: ci

#9960 guix: cleanup manifest
  contrib/guix/libexec/build.sh
  contrib/guix/manifest.scm
Labels: build system

#9661 depends: openssl: update to 3.0.17
  contrib/depends/packages/openssl.mk
Labels: build system

#9958 Add new dynamic fees to ZMQ [0.18]
  src/rpc/daemon_handler.cpp
  src/rpc/daemon_messages.cpp
  src/rpc/daemon_messages.h
Labels: daemon

#9985 crypto: check+throw for Cryptonight v1 invalid input
  src/crypto/hash.h
Labels: cryptography

#9982 rpc: return error correctly on bad key image string [RELEASE]
  src/rpc/core_rpc_server.cpp
Labels: daemon, bugfix

#9855 daemon: Add log-level arg description
  src/daemon/command_line_args.h
Labels: pending review, easy

#9991 ci: bump debian to 11 [0.18]
  .github/workflows/build.yml
Labels: ci

#9994 ci: gitian: update runner to 22.04 [0.18]
  .github/workflows/gitian.yml
Labels: ci

#9996 set do_not_relay always false in submit_multisig_main
  src/simplewallet/simplewallet.cpp
Labels: wallet

#9988 readme: fix macos depends requirements
  README.md
Labels: documentation
