Repository monero-project/monero, pull requests merged in 2025-10, with the labels that each got.

#10109 Daemon RPC: fix on_getblockhash error return on too high height
  src/rpc/core_rpc_server.cpp
Labels: daemon

#10146 cryptonote_basic: rm redundant call to `get_transaction_hash()` in overload
  src/cryptonote_basic/cryptonote_format_utils.cpp
Labels: daemon

#10147 Cleaner validation (faster and saner)
  src/cryptonote_core/blockchain.cpp
  src/cryptonote_core/cryptonote_core.cpp
Labels: daemon

#10148 Cleaner validation (faster and saner) [v0.18]
  src/cryptonote_core/blockchain.cpp
  src/cryptonote_core/cryptonote_core.cpp
Labels: daemon

#10149 cryptonote_basic: rm redundant call to `get_transaction_hash()` in overload [RELEASE]
  src/cryptonote_basic/cryptonote_format_utils.cpp
Labels: daemon

#10150 wallet2: warn instead of throw when RingDB doesn't include spend [v0.18]
  src/wallet/wallet2.cpp
Labels: wallet

#9730 CoC: allow maintainers to merge their own prs if queued
  docs/CONTRIBUTING.md
Labels: documentation

#9732 CoC: don't allow maintainers to edit docs without review
  docs/CONTRIBUTING.md
Labels: documentation

#9733 CoC: do not automatically promote contributors to maintainers
  docs/CONTRIBUTING.md
Labels: documentation

#9735 CoC: remove 'Monero Maintainer Team'
  docs/CONTRIBUTING.md
Labels: documentation

#9737 CoC: remove 'creating stable releases' section
  docs/CONTRIBUTING.md
Labels: documentation

#9743 CoC: remove constraints on 'release history'
  docs/CONTRIBUTING.md
Labels: documentation

#9744 CoC: remove constraint suggesting copyright can be 'owned collectively'
  docs/CONTRIBUTING.md
Labels: documentation

#9748 CoC: prohibit anyone from committing patches to the project directly
  docs/CONTRIBUTING.md
Labels: documentation

#9749 CoC: do not encourage using real names or 'well-known aliases'
  docs/CONTRIBUTING.md
Labels: documentation

#9750 CoC: 'log an issue' -> 'open an issue'
  docs/CONTRIBUTING.md
Labels: documentation
