Repository monero-project/monero, pull requests merged in 2025-09, with the labels that each got.

#10100 tests: only enable fuzz testing if `ENABLE_FUZZ_TEST` defined
  .github/workflows/build.yml
  CMakeLists.txt
  tests/CMakeLists.txt
Labels: tests

#10088 Address warning when building caused by messages_map.cpp string handling
  src/device_trezor/trezor/messages_map.cpp
Labels: cleanup

#10072 cmake: set minimum to 3.10 to fix warnings
  CMakeLists.txt
  README.md
  cmake/FindCcache.cmake
  external/easylogging++/CMakeLists.txt
  translations/CMakeLists.txt
Labels: build system

#10115 net_node: add hinto seed nodes [v0.18]
  src/p2p/net_node.inl
Labels: daemon

#10098 simplewallet: batch address creation limit to match rpc [0.18]
  src/simplewallet/simplewallet.cpp
Labels: wallet
