Repository monero-project/monero, pull requests merged in 2025-08, with the labels that each got.

#10001 guix: build freebsd target with clang 18
  contrib/guix/manifest.scm
Labels: build system

#9995 guix: use canonical repository
  contrib/guix/INSTALL.md
  contrib/guix/libexec/prelude.bash
Labels: build system, ci

#9992 docs: add URI scheme
  docs/URI_SCHEME.md
Labels: documentation

#9984 common: remove `tools::add_element`
  src/common/container_helpers.h
Labels: cleanup

#10014 wallet: deprecate `wallet2::find_and_save_rings()`
  src/simplewallet/simplewallet.cpp
  src/wallet/api/wallet.cpp
  src/wallet/wallet2.cpp
  src/wallet/wallet2.h
Labels: wallet

#10015 wallet: deprecate `wallet2::find_and_save_rings()` [RELEASE]
  src/simplewallet/simplewallet.cpp
  src/wallet/api/wallet.cpp
  src/wallet/wallet2.cpp
  src/wallet/wallet2.h
Labels: wallet

#10020 src: update checkpoints to match v0.18.4.2
  src/blocks/checkpoints.dat
  src/checkpoints/checkpoints.cpp
  src/cryptonote_core/blockchain.cpp
Labels: daemon

#10007 wallet: RPC method /incoming_transfers without daemon connection
  src/wallet/wallet_rpc_server.cpp
Labels: daemon

#10017 simplewallet: fix payment id header in show_transfers command
  src/simplewallet/simplewallet.cpp
Labels: wallet

#10026 cryptonote_basic: remove state_idle in connection_context
  src/cryptonote_basic/connection_context.h
Labels: daemon, cleanup

#10029 Skip ping connections in outgoing count
  contrib/epee/include/net/abstract_tcp_server2.h
  contrib/epee/include/net/abstract_tcp_server2.inl
  src/p2p/net_node.h
  src/p2p/net_node.inl
Labels: daemon

#10031 add depends command for Apple Silicon macOS binaries
  README.md
Labels: documentation

#10033 wallet: fix warning in fee priority algorithm
  src/wallet/fee_algorithm.h
  src/wallet/fee_priority.h
Labels: easy

#10036 epee: include math header for upcoming Boost 1.89
  contrib/epee/src/abstract_http_client.cpp
Labels: build system

#10050 checkpoints: update to a recent block height
  src/blocks/checkpoints.dat
  src/checkpoints/checkpoints.cpp
  src/cryptonote_core/blockchain.cpp
Labels: daemon

#10051 checkpoints: update to a recent block height [release-v0.18]
  src/blocks/checkpoints.dat
  src/checkpoints/checkpoints.cpp
  src/cryptonote_core/blockchain.cpp
Labels: daemon

#10010 guix: switch to guix shell
  contrib/guix/guix-build
  contrib/guix/libexec/build.sh
Labels: build system

#10060 functional_tests: fix piecemeal export in cold_signing, part 2
  tests/functional_tests/cold_signing.py
Labels: tests

#10056 epee: only parse valid port
  contrib/epee/src/net_parse_helpers.cpp
Labels: epee

#10046 BlockchainLMDB: do not assume alignment for alt block entries
  src/blockchain_db/lmdb/db_lmdb.cpp
Labels: database

#10061 ci: macos: reinstall cmake
  .github/workflows/build.yml
Labels: ci

#10063 epee: only parse valid port [release-v0.18]
  contrib/epee/src/net_parse_helpers.cpp
Labels: epee
