Repository monero-project/monero, pull requests merged in 2025-04, with the labels that each got.

#9880 build: set cmake_minimum_required(VERSION 3.5) consistently [release-v0.18]
  CMakeLists.txt
Labels: build system

#9891 guix: remove --user option
  contrib/guix/guix-build
Labels: build system

#9896 guix: ask for confirmation before deleting files
  contrib/guix/guix-clean
Labels: build system

#9904 chore: fix some typos
  src/rpc/core_rpc_server.cpp
Labels: cleanup

#9895 fix inconsistent casing in Dockerfile
  Dockerfile
Labels: build system

#9893 guix: unset HOST env variable
  contrib/guix/guix-build
Labels: build system

#9892 guix: drop support for i686-linux-gnu
  .github/workflows/guix.yml
  contrib/guix/README.md
  contrib/guix/guix-build
Labels: build system

#9889 ci: run brew update
  .github/workflows/build.yml
Labels: ci

#9888 ci: run brew update [0.18]
  .github/workflows/build.yml
Labels: ci

#9887 Fix cmake usage in FetchContent and ExternalProject [0.18]
  cmake/CheckLinkerFlag.cmake
Labels: build system

#9886 Fix cmake usage in FetchContent and ExternalProject
  cmake/CheckLinkerFlag.cmake
Labels: build system

#9876 CMakeLists: add cache option for MANUAL_SUBMODULES
  CMakeLists.txt
Labels: build system

#9873 easylogging: replace NULL with empty string literal
  external/easylogging++/easylogging++.h
Labels: easy

#9863 fix: multisig stale data after failed refresh
  src/wallet/wallet2.cpp
  src/wallet/wallet2.h
Labels: wallet, bugfix

#9857 epee: span::operator[] allow mut ref from const span
  contrib/epee/include/span.h
Labels: easy

#9851 Improve move/copy/default constructor semantics for tx and block
  src/cryptonote_basic/cryptonote_basic.h
  src/cryptonote_core/blockchain.cpp
  src/rpc/rpc_payment.cpp
  src/wallet/wallet2.cpp
Labels: enhancement

#9795 tests: Speed up p2p reorg test
  tests/functional_tests/p2p.py
Labels: tests

#9848 Fix copy in ZMQ input/output
  src/serialization/json_object.h
Labels: enhancement

#9872 construct_tx_and_get_tx_key: don't erase exception trace
  src/cryptonote_core/cryptonote_tx_utils.cpp
Labels: enhancement

#9879 epee: remove reg_exp_definer.h
  contrib/epee/include/net/http_client.h
  contrib/epee/include/net/http_protocol_handler.inl
  contrib/epee/include/reg_exp_definer.h
  contrib/epee/src/net_parse_helpers.cpp
Labels: cleanup

#9881 epee: syncobj: replace shims with Boost classes
  contrib/epee/include/net/levin_protocol_handler_async.h
  contrib/epee/include/syncobj.h
  src/cryptonote_protocol/cryptonote_protocol_handler-base.cpp
  src/wallet/api/wallet_manager.cpp
  tests/libwallet_api_tests/main.cpp
Labels: cleanup, epee

#9911 fix: multisig stale data after failed refresh [release v0.18]
  src/wallet/wallet2.cpp
  src/wallet/wallet2.h
Labels: wallet, bugfix

#9404 cryptonote_core: only verify txpool when the hardfork value has changed.
  src/cryptonote_core/cryptonote_core.cpp
Labels: enhancement

#9875 wallet: fix monero-wallet-rpc ignoring calls during sync
  src/wallet/wallet_rpc_server.cpp
  src/wallet/wallet_rpc_server.h
Labels: enhancement, wallet

#9916 msys2 build: include int headers
  contrib/epee/include/serialization/keyvalue_serialization_overloads.h
  src/common/perf_timer.h
Labels: easy
