Repository monero-project/monero, pull requests merged in 2025-03, with the labels that each got.

#9135 blockchain sync: reduce disk writes from 2 to 1 per tx
  src/blockchain_utilities/blockchain_import.cpp
  src/cryptonote_basic/cryptonote_format_utils.cpp
  src/cryptonote_basic/cryptonote_format_utils.h
  src/cryptonote_basic/verification_context.h
  src/cryptonote_core/blockchain.cpp
  src/cryptonote_core/blockchain.h
  src/cryptonote_core/cryptonote_core.cpp
  src/cryptonote_core/cryptonote_core.h
  src/cryptonote_core/tx_pool.cpp
  src/cryptonote_core/tx_pool.h
  src/cryptonote_core/tx_verification_utils.cpp
  src/cryptonote_core/tx_verification_utils.h
  src/cryptonote_protocol/cryptonote_protocol_handler.h
  src/cryptonote_protocol/cryptonote_protocol_handler.inl
  src/cryptonote_protocol/cryptonote_protocol_handler_common.h
  src/daemon/command_parser_executor.cpp
  src/daemon/daemon.cpp
  src/daemon/rpc_command_executor.cpp
  src/daemon/rpc_command_executor.h
  src/rpc/core_rpc_server.cpp
  src/rpc/core_rpc_server_commands_defs.h
  src/rpc/daemon_handler.cpp
  tests/core_tests/chaingen.h
  tests/functional_tests/p2p.py
  tests/unit_tests/node_server.cpp
Labels: enhancement, important, daemon, consensus

#9820 Add incoming only test
  contrib/epee/include/net/abstract_tcp_server2.inl
Labels: easy, networking, bugfix

#9823 Add incoming only test [0.18]
  contrib/epee/include/net/abstract_tcp_server2.inl
Labels: easy, networking, bugfix

#9807 depends: boost: update to 1.69.0 [0.18]
  CMakeLists.txt
  contrib/depends/Makefile
  contrib/depends/packages/boost.mk
Labels: build system

#9850 trezor: fix protobuf 30 compatibility [0.18]
  cmake/CheckTrezor.cmake
  src/device_trezor/trezor/messages_map.cpp
  src/device_trezor/trezor/messages_map.hpp
Labels: build system

#9824 chore: fix some typos in comments
  Doxyfile
  src/device_trezor/device_trezor.cpp
  tests/libwallet_api_tests/scripts/README.md
  tests/trezor/daemon.h
  tests/unit_tests/levin.cpp
Labels: cleanup

#9832 wallet: fix different-signedness int comparison warnings
  src/wallet/wallet2.cpp
Labels: easy, wallet

#9836 cryptonote_basic: remove unused struct [0.18]
  src/cryptonote_basic/cryptonote_basic_impl.h
Labels: cleanup

#9845 Blockchain: remove skip for pruned txs in `check_tx_inputs()`
  src/cryptonote_core/blockchain.cpp
Labels: daemon

#9846 Remove hidden transaction copy in add_block
  src/blockchain_db/blockchain_db.cpp
  src/blockchain_db/blockchain_db.h
  src/blockchain_db/lmdb/db_lmdb.cpp
  src/blockchain_db/lmdb/db_lmdb.h
  src/blockchain_db/testdb.h
Labels: daemon

#9853 cryptonote_protocol: fix handling of pruned blocks during sync [RELEASE]
  src/cryptonote_core/blockchain.cpp
  src/cryptonote_protocol/cryptonote_protocol_handler.inl
Labels: bugfix

#9809 logging: Fix easylogging++ init with blank config
  external/easylogging++/easylogging++.h
  tests/unit_tests/logging.cpp
Labels: enhancement

#9821 Fix HTTP unit tests (broken with new Boost versions)
  tests/unit_tests/epee_http_server.cpp
Labels: pending review, tests

#9791 ci: introduce rust toolchain
  .github/workflows/build.yml
  .github/workflows/depends.yml
Labels: ci, fcmp++

#9840 trezor: fix cmake variables
  cmake/CheckTrezor.cmake
Labels: build system

#9862 Fix expected hash check [0.18]
  src/cryptonote_basic/connection_context.cpp
Labels: bugfix

#9861 Fix expected hash check
  src/cryptonote_basic/connection_context.cpp
Labels: bugfix

#9842 wallet: Correct max / min block waiting periods for estimated_backlog in wallet2.cpp
  src/wallet/wallet2.cpp
Labels: pending review, wallet, bugfix

#9867 wallet: Correct max / min block waiting periods for estimated_backlog in wallet2.cpp [RELEASE]
  src/wallet/wallet2.cpp
Labels: wallet, bugfix

#9864 checkpoints: update to a recent block height [release-v0.18]
  src/blocks/checkpoints.dat
  src/checkpoints/checkpoints.cpp
  src/cryptonote_core/blockchain.cpp
Labels: pending review, daemon
